version: '3'
services:
    neo4j:
        image: neo4j:4.3.1-community
        container_name: neo4jNode
        ports: 
            - "7474:7474"
            - "7687:7687"
        volumes: 
            - ./data/:/data
            # - ./logs/:$HOME/neo4j/logs
            # - ./import/:$HOME/neo4j/import